### ISSUE TITLE
Monkey-patch the linter to break patched specs

### ISSUE THREAD

**Issue by mrackwitz** [orta/cocoapods-expert-difficulty#1]
Monkey-patching `Specification#supported_platforms` will cause not only that any podspec can be used in a integration via Podfile for a target definition of a non supported platform, but also that any podspec can be successfully linted, even if it's using dependencies, which don't support all it's target platforms. I don't think that should happen.

**Comment by orta** [comment]
This won't do that, we add checks to make sure [it's defined in the podfile](https://github.com/orta/cocoapods-expert-difficulty/blob/master/lib/cocoapods_plugin.rb#L27). Linting won't do that.

**Comment by mrackwitz** [comment]
Right, the linter uses an on-the-fly created podfile. :+1:
